# Generated by Django 4.1 on 2022-08-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchagain',
            new_name='watchAgain',
        ),
    ]
